#!/usr/bin/env node
/*
 * Samples the Vector mark (the "V" plus its magenta arrow) onto a regular grid,
 * so the transition can build the shape out of tiny arrows.
 *
 *   node animation/tools/sample-mark.js [--spacing 3.2]
 *
 * Spacing is in the logo artwork's own units (the mark is 105.425 x 118.046 of
 * them). Points come out in those units too, so the runtime is free to scale the
 * mark to whatever size the Domino screen calls for.
 *
 * Baking these at build time rather than sampling a canvas at runtime keeps the
 * animation a pure function of t — which is what makes it seekable, and therefore
 * exportable frame by frame.
 */
const fs = require('fs');
const path = require('path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '/opt/node22/lib/node_modules/playwright');

const dir = path.resolve(__dirname, '..');
const SVG = path.join(dir, 'assets', 'vector-logo-horizontal.svg');
const OUT = path.join(dir, 'assets', 'mark-points.js');

const spacingArg = process.argv.indexOf('--spacing');
const SPACING = spacingArg === -1 ? 3.2 : Number(process.argv[spacingArg + 1]);
const SUPERSAMPLE = 6; // raster px per artwork unit — plenty to resolve thin details

(async () => {
  const svg = fs.readFileSync(SVG, 'utf8');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 900, height: 900 } });
  await page.setContent(`<body style="margin:0">${svg}</body>`);

  const result = await page.evaluate(
    async ({ spacing, ss }) => {
      const src = document.querySelector('svg');
      const mark = document.getElementById('mark');
      const box = mark.getBBox();

      // Re-issue the mark alone, cropped to its own bounding box.
      const lone =
        `<svg xmlns="http://www.w3.org/2000/svg" width="${box.width * ss}" ` +
        `height="${box.height * ss}" viewBox="${box.x} ${box.y} ${box.width} ${box.height}">` +
        mark.outerHTML +
        '</svg>';

      const img = new Image();
      await new Promise((done, fail) => {
        img.onload = done;
        img.onerror = fail;
        img.src = 'data:image/svg+xml,' + encodeURIComponent(lone);
      });

      const cv = document.createElement('canvas');
      cv.width = Math.round(box.width * ss);
      cv.height = Math.round(box.height * ss);
      const ctx = cv.getContext('2d', { willReadFrequently: true });
      ctx.drawImage(img, 0, 0, cv.width, cv.height);
      const px = ctx.getImageData(0, 0, cv.width, cv.height).data;

      const points = [];
      let white = 0;
      let magenta = 0;
      for (let gy = spacing / 2; gy < box.height; gy += spacing) {
        for (let gx = spacing / 2; gx < box.width; gx += spacing) {
          const sx = Math.min(cv.width - 1, Math.round(gx * ss));
          const sy = Math.min(cv.height - 1, Math.round(gy * ss));
          const i = (sy * cv.width + sx) * 4;
          if (px[i + 3] < 160) continue; // outside the shape
          // The mark has exactly two fills: white, and a magenta that is nearly
          // saturated in red and blue with little green.
          const isMagenta = px[i + 1] < 140;
          points.push([+gx.toFixed(3), +gy.toFixed(3), isMagenta ? 1 : 0]);
          isMagenta ? magenta++ : white++;
        }
      }
      return {
        width: +box.width.toFixed(4),
        height: +box.height.toFixed(4),
        points,
        white,
        magenta,
        srcViewBox: src.getAttribute('viewBox'),
        markX: +box.x.toFixed(4),
        markY: +box.y.toFixed(4),
      };
    },
    { spacing: SPACING, ss: SUPERSAMPLE }
  );

  await browser.close();

  const js =
    '/* Generated by animation/tools/sample-mark.js — do not edit by hand. */\n' +
    `/* The Vector mark on a ${SPACING}-unit grid: ${result.points.length} points ` +
    `(${result.white} white, ${result.magenta} magenta). */\n` +
    'const MARK_POINTS = ' +
    JSON.stringify(
      {
        width: result.width,
        height: result.height,
        spacing: SPACING,
        markX: result.markX,
        markY: result.markY,
        logoViewBox: result.srcViewBox,
        points: result.points,
      },
      null,
      0
    ) +
    ';\n' +
    "if (typeof module !== 'undefined' && module.exports) module.exports = { MARK_POINTS };\n";

  fs.writeFileSync(OUT, js);
  console.log(
    `${result.points.length} points (${result.white} white, ${result.magenta} magenta) ` +
      `over ${result.width} x ${result.height} at spacing ${SPACING}`
  );
  console.log(`magenta share ${((result.magenta / result.points.length) * 100).toFixed(1)}%`);
  console.log(`${(fs.statSync(OUT).size / 1024).toFixed(0)} KB -> ${OUT}`);
})();
